<?php

/**
 * Implements hook_menu().
 */
function commerce_order_receipt_menu() {

  $items['admin/commerce/orders/%commerce_order/print_receipt'] = array(
    'title' => 'Print receipt',
    'page callback' => 'commerce_order_receipt_print_order',
    'page arguments' => array(3),
    'access callback' => 'commerce_order_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => -5,
  );
  return $items;
}

function commerce_order_receipt_print_order($order) {
  module_load_include('inc', 'phpexcel');
  $headers = array();
  $data[] = array('Товарный чек №' . $order->order_id . ' от ' . format_date($order->created, 'short'));
  $data[] = array('ИП (ФИО) Файзулин Иван Рамильевич');
  $data[] = array('ИНН 420541005930 ОГРНИП 312420531200050');
  $data[] = array(
    'Наименование товара',
    'Количество',
    'Цена',
    'Сумма',
  );
  dsm($order);

  foreach($order->commerce_line_items ['und'] as $value) {
    $line_item = commerce_line_item_load($value['line_item_id']);
    // Add the order line items
    $row[] = array(
      $line_item->line_item_label,
      $line_item->quantity,
      $line_item->commerce_unit_price['und'][0]['amount'] / 100 . ' руб.',
      $line_item->commerce_total['und'][0]['amount'] / 100 . ' руб.',
    );
  }
  $data = array_merge($data, $row);
  $data[] = array('Наличие кассового чека обязательно');
  $data[] = array('Итого ' .  $order->commerce_order_total['und'][0]['amount'] / 100 . ' рублей.    Подпись');
  // Store the file in sites/default/files
  $dir = file_stream_wrapper_get_instance_by_uri('public://')->realpath();
  $filename = 'Order receipt №' . $order->order_id . '.xls';
  $path = "$dir/$filename";
  // Use the .xls format
  $options = array('format' => 'xls', 'ignore_headers' => TRUE);
  $result = phpexcel_export($headers, $data, $path, $options);
  if ($result == PHPEXCEL_SUCCESS) {
    drupal_set_message(t("We did it !"));
  }
  else {
    drupal_set_message(t("Oops ! An error occured !"), 'error');
  }
  drupal_goto('admin/commerce/orders/list');
}

/*
 * Add our link to contextual links.
 */
function commerce_order_receipt_menu_contextual_links_alter(&$links, $router_item, $root_path) {
  if($root_path == 'admin/commerce/orders/%') {
    $link = $links['commerce-order-view']['tab_root_href'];
    $parts = explode('/', $link);
    $order_id = array_pop($parts);
    $new_link = menu_get_item(str_replace('%', $order_id, 'admin/commerce/orders/%/print_receipt'));
    $links['commerce-order-receipt'] = $new_link;
  }

}